spring.application.name=cargo-gateway
server.port=8081

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Spring Boot'un Freemarker autoconfigure'ini kapat
# (biz Freemarker'i manuel yonetiyoruz, cakisma olmasin)
spring.freemarker.enabled=false
spring.cloud.openfeign.okhttp.enabled=true

logging.level.feign=DEBUG
logging.level.okhttp3=DEBUG

# ── PTT ──────────────────────────────────────────────────────────────────────
# cargo-gateway, PTT'ye dogrudan SOAP atmaz.
# ptt-cargo-api adli ayri Spring Boot projesine REST ile baglanir.
# O proje port 8080'de calismalidir.
ptt-service.base-url=http://localhost:8080

# ── Yurtici Kargo ────────────────────────────────────────────────────────────
# Test:  https://testws.yurticikargo.com/KOPSWebServices/ShippingOrderDispatcherServices
# Canli: https://ws.yurticikargo.com/KOPSWebServices/ShippingOrderDispatcherServices
yurtici.base-url=https://testws.yurticikargo.com/KOPSWebServices/ShippingOrderDispatcherServices
yurtici.username=YKTEST
yurtici.password=YK
yurtici.user-language=TR

# ── MNG Kargo ────────────────────────────────────────────────────────────────
# Sandbox: https://sandbox.mngkargo.com.tr
# Uretim:  https://apizone.mngkargo.com.tr
# Client ID ve Secret: sandbox.mngkargo.com.tr -> Uygulamalar -> Yeni Uygulama
# (Secret Key sadece olusturulurken 1 kez gosterilir, kaydedin!)
mng.base-url=https://testapi.mngkargo.com.tr
mng.client-id=3cdf0a4013ddb06d51ca4a2f8058d5e8
mng.client-secret=27dca28e82d86a7fe813674764450e9b
mng.customer-number=94700902
mng.password=Techpo*1234
mng.token-ttl-minutes=480
